env:
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:json/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - prettier
  - json
settings:
  react:
    version: detect
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - error
  no-template-curly-in-string:
    - error
  array-callback-return:
    - error
  block-scoped-var:
    - error
  class-methods-use-this:
    - error
  curly:
    - error
    - multi-line
    - consistent
  consistent-return:
    - error
  dot-notation:
    - error
  dot-location:
    - error
    - property
  eqeqeq:
    - error
    - smart
  no-else-return:
    - error
  no-extra-bind:
    - error
  no-eval:
    - error
  no-floating-decimal:
    - error
  no-implicit-globals:
    - error
  no-invalid-this:
    - error
  no-multi-spaces:
    - error
  no-shadow:
    - error
  no-use-before-define:
    - error
  prettier/prettier:
    - error
  react/prop-types:
    - off
overrides:
  - files:
      - src/**
    env:
      browser: true
      es2020: true
  - files:
      - dev/**
    env:
      node: true
      es2020: true
